import fs from "node:fs";
import path from "node:path";
import { describe, expect, test } from "vitest";
import { TSurveyElementTypeEnum } from "@formbricks/types/surveys/elements";

/**
 * The public API reference at `docs/api-reference/openapi.json` is hand-maintained: nothing generates it from
 * `TSurveyElementTypeEnum`, so the two can drift apart silently. When they do, the symptom is not a build
 * failure but a published contract that under-reports what the API accepts - integrators simply never learn
 * the element type exists.
 *
 * This suite is the missing link. It reads the document off disk, locates the element type enum structurally
 * rather than by line number, and holds it set-equal to the shared enum in both directions.
 *
 * Two deliberate choices are worth stating. The comparison is over *sets*, never over arrays: the document
 * lists the values in a different order from the enum declaration (`cal` sits after `rating` there, and
 * `contactInfo` near the end), and that ordering carries no meaning, so requiring it would be noise. And the
 * enum is located by walking the document, which additionally lets the suite prove there is exactly one such
 * enum - a second, stale copy pasted in elsewhere would otherwise be invisible.
 *
 * The v2 reference at `docs/api-v2-reference/openapi.yml` is deliberately not covered: it is generated by its
 * own tooling rather than hand-maintained, so it cannot drift in this way.
 */

const OPENAPI_PATH = path.resolve(__dirname, "../../../../docs/api-reference/openapi.json");

type JsonValue = string | number | boolean | null | JsonValue[] | { [key: string]: JsonValue };

const openApiDocument = JSON.parse(fs.readFileSync(OPENAPI_PATH, "utf-8")) as JsonValue;

/**
 * Where the element type enum lives in the document. Recorded as a pointer so a restructure of the document
 * produces a failure that names the exact segment that moved, instead of a bare `undefined`.
 */
const ELEMENT_TYPE_ENUM_POINTER = [
  "paths",
  "/api/v1/management/surveys",
  "post",
  "requestBody",
  "content",
  "application/json",
  "schema",
  "properties",
  "questions",
  "items",
  "properties",
  "type",
] as const;

function isRecord(value: JsonValue): value is { [key: string]: JsonValue } {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

/** Walks the pointer, failing with the traversed prefix so a moved node is immediately identifiable. */
function resolvePointer(root: JsonValue, pointer: readonly string[]): JsonValue {
  let current = root;
  const walked: string[] = [];

  for (const segment of pointer) {
    if (!isRecord(current) || !(segment in current)) {
      throw new Error(
        `the OpenAPI document has no "${segment}" under [${walked.join(" > ")}] - the element type enum has moved, so this pointer needs updating`
      );
    }
    current = current[segment];
    walked.push(segment);
  }

  return current;
}

/**
 * Every array in the document that looks like an element type enum, keyed by where it was found. `openText`
 * is the probe: it is the one element type whose name appears in no other enumeration in the document.
 */
function collectElementTypeEnums(root: JsonValue): { pointer: string; values: string[] }[] {
  const found: { pointer: string; values: string[] }[] = [];

  const walk = (node: JsonValue, trail: string[]): void => {
    if (Array.isArray(node)) {
      if (node.includes("openText")) {
        found.push({
          pointer: trail.join(" > "),
          values: node.filter((entry): entry is string => typeof entry === "string"),
        });
      }
      node.forEach((entry, index) => walk(entry, [...trail, String(index)]));
      return;
    }
    if (isRecord(node)) {
      for (const [key, value] of Object.entries(node)) {
        walk(value, [...trail, key]);
      }
    }
  };

  walk(root, []);
  return found;
}

const elementTypeSchema = resolvePointer(openApiDocument, ELEMENT_TYPE_ENUM_POINTER);
const declaredEnum = isRecord(elementTypeSchema) ? elementTypeSchema.enum : undefined;
const openApiElementTypes = Array.isArray(declaredEnum)
  ? declaredEnum.filter((entry): entry is string => typeof entry === "string")
  : [];

const sharedElementTypes = Object.values(TSurveyElementTypeEnum) as string[];

describe("OpenAPI element type enum", () => {
  describe("document structure", () => {
    test("the hand-maintained reference is present and parses", () => {
      expect(fs.existsSync(OPENAPI_PATH)).toBe(true);
      expect(isRecord(openApiDocument)).toBe(true);
    });

    test("the element type enum sits where this suite expects it", () => {
      expect(isRecord(elementTypeSchema)).toBe(true);
      expect(Array.isArray(declaredEnum)).toBe(true);
    });

    test("is declared as a string enum", () => {
      expect(isRecord(elementTypeSchema) ? elementTypeSchema.type : undefined).toBe("string");
      expect(openApiElementTypes).toHaveLength(Array.isArray(declaredEnum) ? declaredEnum.length : -1);
    });

    test("appears exactly once in the document", () => {
      // A second copy pasted in elsewhere would drift independently and silently.
      const enums = collectElementTypeEnums(openApiDocument);
      expect(enums).toHaveLength(1);
      expect(enums[0].pointer).toBe([...ELEMENT_TYPE_ENUM_POINTER, "enum"].join(" > "));
    });

    test("lists no value twice", () => {
      expect([...new Set(openApiElementTypes)]).toHaveLength(openApiElementTypes.length);
    });
  });

  describe("synchronization with TSurveyElementTypeEnum", () => {
    test("advertises the slider element type", () => {
      // The minimum the public contract owes this feature: without it, the API accepts a type it never
      // documents.
      expect(openApiElementTypes).toContain(TSurveyElementTypeEnum.Slider);
      expect(openApiElementTypes).toContain("slider");
    });

    test("matches the shared enum exactly", () => {
      // Sorted, because the document's ordering differs from the declaration's and carries no meaning.
      expect([...openApiElementTypes].sort()).toEqual([...sharedElementTypes].sort());
    });

    test("documents every element type the shared enum declares", () => {
      const undocumented = sharedElementTypes.filter((type) => !openApiElementTypes.includes(type));
      expect(undocumented).toEqual([]);
    });

    test("documents no element type the shared enum does not declare", () => {
      const unknown = openApiElementTypes.filter((type) => !sharedElementTypes.includes(type));
      expect(unknown).toEqual([]);
    });

    test("has one entry per shared enum member", () => {
      expect(openApiElementTypes).toHaveLength(sharedElementTypes.length);
    });

    test("covers eighteen element types", () => {
      // A deliberate tripwire on the count itself, so introducing a nineteenth element type forces a
      // conscious visit to this file rather than passing on set equality alone once both sides are updated.
      expect(sharedElementTypes).toHaveLength(18);
      expect(openApiElementTypes).toHaveLength(18);
    });

    test("still documents the element types that predate the slider", () => {
      // Guards against a fix to this suite that satisfies set equality by trimming the document.
      expect(openApiElementTypes).toContain(TSurveyElementTypeEnum.OpinionScale);
      expect(openApiElementTypes).toContain(TSurveyElementTypeEnum.Payment);
      expect(openApiElementTypes).toContain(TSurveyElementTypeEnum.OpenText);
    });
  });
});
